"""Initial migration

Revision ID: 075b5d579e58
Revises: 18384f476ba4
Create Date: 2026-01-09 16:10:45.643215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075b5d579e58'
down_revision: Union[str, Sequence[str], None] = '18384f476ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publication_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publication_date')
    # ### end Alembic commands ###
